// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvK3gBetSxKYSvsZe25oTWJNfKOVXWep0',
    appId: '1:411477698947:web:afe5f1422681477c8feeb6',
    messagingSenderId: '411477698947',
    projectId: 'chat-b1e84',
    authDomain: 'chat-b1e84.firebaseapp.com',
    databaseURL: 'https://chat-b1e84-default-rtdb.firebaseio.com',
    storageBucket: 'chat-b1e84.firebasestorage.app',
    measurementId: 'G-DTEGHBMJVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9_1j5FHofgBsd61vRi3HvuBopG12zjgQ',
    appId: '1:411477698947:android:a88767e2f647f56c8feeb6',
    messagingSenderId: '411477698947',
    projectId: 'chat-b1e84',
    databaseURL: 'https://chat-b1e84-default-rtdb.firebaseio.com',
    storageBucket: 'chat-b1e84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4IRvyhua2zIHp2DkhPnm-p7xRMBPIi4',
    appId: '1:411477698947:ios:3665ad2c3a4232568feeb6',
    messagingSenderId: '411477698947',
    projectId: 'chat-b1e84',
    databaseURL: 'https://chat-b1e84-default-rtdb.firebaseio.com',
    storageBucket: 'chat-b1e84.firebasestorage.app',
    iosBundleId: 'com.example.doanLttdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4IRvyhua2zIHp2DkhPnm-p7xRMBPIi4',
    appId: '1:411477698947:ios:3665ad2c3a4232568feeb6',
    messagingSenderId: '411477698947',
    projectId: 'chat-b1e84',
    databaseURL: 'https://chat-b1e84-default-rtdb.firebaseio.com',
    storageBucket: 'chat-b1e84.firebasestorage.app',
    iosBundleId: 'com.example.doanLttdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvK3gBetSxKYSvsZe25oTWJNfKOVXWep0',
    appId: '1:411477698947:web:d12e5053489175da8feeb6',
    messagingSenderId: '411477698947',
    projectId: 'chat-b1e84',
    authDomain: 'chat-b1e84.firebaseapp.com',
    databaseURL: 'https://chat-b1e84-default-rtdb.firebaseio.com',
    storageBucket: 'chat-b1e84.firebasestorage.app',
    measurementId: 'G-M1VNGCSCFL',
  );
}
